[2023-07-14 07:43:37,940] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-21T14:01:41+00:00 [queued]>
[2023-07-14 07:43:38,048] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-21T14:01:41+00:00 [queued]>
[2023-07-14 07:43:38,049] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-07-14 07:43:38,049] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-07-14 07:43:38,050] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-07-14 07:43:38,119] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): create_user> on 2023-06-21T14:01:41+00:00
[2023-07-14 07:43:38,123] {standard_task_runner.py:52} INFO - Started process 27180 to run task
[2023-07-14 07:43:38,135] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'create_user', '2023-06-21T14:01:41+00:00', '--job-id', '12522', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag/test.py', '--cfg-path', '/tmp/tmp59aibuc2', '--error-file', '/tmp/tmpt2vu1lct']
[2023-07-14 07:43:38,136] {standard_task_runner.py:77} INFO - Job 12522: Subtask create_user
[2023-07-14 07:43:38,230] {logging_mixin.py:104} INFO - Running <TaskInstance: my_first_dag.create_user 2023-06-21T14:01:41+00:00 [running]> on host d9c3ec86c3ab
[2023-07-14 07:43:38,611] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=create_user
AIRFLOW_CTX_EXECUTION_DATE=2023-06-21T14:01:41+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-21T14:01:41+00:00
[2023-07-14 07:43:38,614] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-07-14 07:43:38,616] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\nid -u test_user;\nif [$? -eq o];\n    then echo "User exists"\nelse sudo useradd -r test_user;\n    echo "User created";\nfi']
[2023-07-14 07:43:38,626] {subprocess.py:75} INFO - Output:
[2023-07-14 07:43:38,696] {subprocess.py:79} INFO - id: ‘test_user’: no such user
[2023-07-14 07:43:38,703] {subprocess.py:79} INFO - bash: line 2: [1: command not found
[2023-07-14 07:43:38,764] {subprocess.py:79} INFO - 
[2023-07-14 07:43:38,765] {subprocess.py:79} INFO - We trust you have received the usual lecture from the local System
[2023-07-14 07:43:38,765] {subprocess.py:79} INFO - Administrator. It usually boils down to these three things:
[2023-07-14 07:43:38,766] {subprocess.py:79} INFO - 
[2023-07-14 07:43:38,766] {subprocess.py:79} INFO -     #1) Respect the privacy of others.
[2023-07-14 07:43:38,767] {subprocess.py:79} INFO -     #2) Think before you type.
[2023-07-14 07:43:38,768] {subprocess.py:79} INFO -     #3) With great power comes great responsibility.
[2023-07-14 07:43:38,768] {subprocess.py:79} INFO - 
[2023-07-14 07:43:38,769] {subprocess.py:79} INFO - sudo: no tty present and no askpass program specified
[2023-07-14 07:43:38,775] {subprocess.py:79} INFO - User created
[2023-07-14 07:43:38,779] {subprocess.py:83} INFO - Command exited with return code 0
[2023-07-14 07:43:38,852] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=create_user, execution_date=20230621T140141, start_date=20230714T074337, end_date=20230714T074338
[2023-07-14 07:43:38,925] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-14 07:43:38,950] {local_task_job.py:151} INFO - Task exited with return code 0
