[2023-07-11 11:57:46,683] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-17T14:01:01+00:00 [queued]>
[2023-07-11 11:57:46,818] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-17T14:01:01+00:00 [queued]>
[2023-07-11 11:57:46,819] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-07-11 11:57:46,820] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-07-11 11:57:46,822] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-07-11 11:57:46,901] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): create_user> on 2023-06-17T14:01:01+00:00
[2023-07-11 11:57:46,910] {standard_task_runner.py:52} INFO - Started process 19967 to run task
[2023-07-11 11:57:46,932] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'create_user', '2023-06-17T14:01:01+00:00', '--job-id', '6664', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag/test.py', '--cfg-path', '/tmp/tmpndvjt5lf', '--error-file', '/tmp/tmphfzw2dry']
[2023-07-11 11:57:46,934] {standard_task_runner.py:77} INFO - Job 6664: Subtask create_user
[2023-07-11 11:57:47,056] {logging_mixin.py:104} INFO - Running <TaskInstance: my_first_dag.create_user 2023-06-17T14:01:01+00:00 [running]> on host d9c3ec86c3ab
[2023-07-11 11:57:47,384] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=create_user
AIRFLOW_CTX_EXECUTION_DATE=2023-06-17T14:01:01+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-17T14:01:01+00:00
[2023-07-11 11:57:47,387] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-07-11 11:57:47,389] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\nid -u test_user;\nif [$? -eq o];\n    then echo "User exists"\nelse sudo useradd -r test_user;\n    echo "User created";\nfi']
[2023-07-11 11:57:47,403] {subprocess.py:75} INFO - Output:
[2023-07-11 11:57:47,480] {subprocess.py:79} INFO - id: ‘test_user’: no such user
[2023-07-11 11:57:47,488] {subprocess.py:79} INFO - bash: line 2: [1: command not found
[2023-07-11 11:57:47,556] {subprocess.py:79} INFO - 
[2023-07-11 11:57:47,557] {subprocess.py:79} INFO - We trust you have received the usual lecture from the local System
[2023-07-11 11:57:47,559] {subprocess.py:79} INFO - Administrator. It usually boils down to these three things:
[2023-07-11 11:57:47,560] {subprocess.py:79} INFO - 
[2023-07-11 11:57:47,560] {subprocess.py:79} INFO -     #1) Respect the privacy of others.
[2023-07-11 11:57:47,561] {subprocess.py:79} INFO -     #2) Think before you type.
[2023-07-11 11:57:47,562] {subprocess.py:79} INFO -     #3) With great power comes great responsibility.
[2023-07-11 11:57:47,563] {subprocess.py:79} INFO - 
[2023-07-11 11:57:47,566] {subprocess.py:79} INFO - sudo: no tty present and no askpass program specified
[2023-07-11 11:57:47,573] {subprocess.py:79} INFO - User created
[2023-07-11 11:57:47,578] {subprocess.py:83} INFO - Command exited with return code 0
[2023-07-11 11:57:47,647] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=create_user, execution_date=20230617T140101, start_date=20230711T115746, end_date=20230711T115747
[2023-07-11 11:57:47,740] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-11 11:57:47,784] {local_task_job.py:151} INFO - Task exited with return code 0
