[2023-06-28 17:07:40,040] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-15T18:01:32+00:00 [queued]>
[2023-06-28 17:07:40,232] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-15T18:01:32+00:00 [queued]>
[2023-06-28 17:07:40,234] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-06-28 17:07:40,236] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-06-28 17:07:40,237] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-06-28 17:07:40,336] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): create_user> on 2023-06-15T18:01:32+00:00
[2023-06-28 17:07:40,381] {standard_task_runner.py:52} INFO - Started process 8660 to run task
[2023-06-28 17:07:40,406] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'create_user', '2023-06-15T18:01:32+00:00', '--job-id', '4032', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag/test.py', '--cfg-path', '/tmp/tmptb6jha79', '--error-file', '/tmp/tmpy32vy_ca']
[2023-06-28 17:07:40,409] {standard_task_runner.py:77} INFO - Job 4032: Subtask create_user
[2023-06-28 17:07:40,761] {logging_mixin.py:104} INFO - Running <TaskInstance: my_first_dag.create_user 2023-06-15T18:01:32+00:00 [running]> on host d9c3ec86c3ab
[2023-06-28 17:07:41,254] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=create_user
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T18:01:32+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-15T18:01:32+00:00
[2023-06-28 17:07:41,261] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-06-28 17:07:41,265] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\nid -u test_user;\nif [$? -eq o];\n    then echo "User exists"\nelse sudo useradd -r test_user;\n    echo "User created";\nfi']
[2023-06-28 17:07:41,286] {subprocess.py:75} INFO - Output:
[2023-06-28 17:07:41,384] {subprocess.py:79} INFO - id: ‘test_user’: no such user
[2023-06-28 17:07:41,398] {subprocess.py:79} INFO - bash: line 2: [1: command not found
[2023-06-28 17:07:41,502] {subprocess.py:79} INFO - 
[2023-06-28 17:07:41,504] {subprocess.py:79} INFO - We trust you have received the usual lecture from the local System
[2023-06-28 17:07:41,505] {subprocess.py:79} INFO - Administrator. It usually boils down to these three things:
[2023-06-28 17:07:41,506] {subprocess.py:79} INFO - 
[2023-06-28 17:07:41,508] {subprocess.py:79} INFO -     #1) Respect the privacy of others.
[2023-06-28 17:07:41,509] {subprocess.py:79} INFO -     #2) Think before you type.
[2023-06-28 17:07:41,511] {subprocess.py:79} INFO -     #3) With great power comes great responsibility.
[2023-06-28 17:07:41,513] {subprocess.py:79} INFO - 
[2023-06-28 17:07:41,515] {subprocess.py:79} INFO - sudo: no tty present and no askpass program specified
[2023-06-28 17:07:41,519] {subprocess.py:79} INFO - User created
[2023-06-28 17:07:41,522] {subprocess.py:83} INFO - Command exited with return code 0
[2023-06-28 17:07:41,666] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=create_user, execution_date=20230615T180132, start_date=20230628T170740, end_date=20230628T170741
[2023-06-28 17:07:41,949] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-28 17:07:41,997] {local_task_job.py:151} INFO - Task exited with return code 0
