[2023-07-17 13:35:30,229] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-22T09:01:49+00:00 [queued]>
[2023-07-17 13:35:30,597] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-22T09:01:49+00:00 [queued]>
[2023-07-17 13:35:30,600] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-07-17 13:35:30,602] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-07-17 13:35:30,605] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-07-17 13:35:31,019] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): create_user> on 2023-06-22T09:01:49+00:00
[2023-07-17 13:35:31,029] {standard_task_runner.py:52} INFO - Started process 11354 to run task
[2023-07-17 13:35:31,049] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'create_user', '2023-06-22T09:01:49+00:00', '--job-id', '13681', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag/test.py', '--cfg-path', '/tmp/tmp7dfidugo', '--error-file', '/tmp/tmp8kymmc20']
[2023-07-17 13:35:31,052] {standard_task_runner.py:77} INFO - Job 13681: Subtask create_user
[2023-07-17 13:35:31,299] {logging_mixin.py:104} INFO - Running <TaskInstance: my_first_dag.create_user 2023-06-22T09:01:49+00:00 [running]> on host d9c3ec86c3ab
[2023-07-17 13:35:32,458] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=create_user
AIRFLOW_CTX_EXECUTION_DATE=2023-06-22T09:01:49+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-22T09:01:49+00:00
[2023-07-17 13:35:32,462] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-07-17 13:35:32,464] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\nid -u test_user;\nif [$? -eq o];\n    then echo "User exists"\nelse sudo useradd -r test_user;\n    echo "User created";\nfi']
[2023-07-17 13:35:32,484] {subprocess.py:75} INFO - Output:
[2023-07-17 13:35:32,580] {subprocess.py:79} INFO - id: ‘test_user’: no such user
[2023-07-17 13:35:32,591] {subprocess.py:79} INFO - bash: line 2: [1: command not found
[2023-07-17 13:35:32,677] {subprocess.py:79} INFO - 
[2023-07-17 13:35:32,678] {subprocess.py:79} INFO - We trust you have received the usual lecture from the local System
[2023-07-17 13:35:32,679] {subprocess.py:79} INFO - Administrator. It usually boils down to these three things:
[2023-07-17 13:35:32,680] {subprocess.py:79} INFO - 
[2023-07-17 13:35:32,680] {subprocess.py:79} INFO -     #1) Respect the privacy of others.
[2023-07-17 13:35:32,681] {subprocess.py:79} INFO -     #2) Think before you type.
[2023-07-17 13:35:32,682] {subprocess.py:79} INFO -     #3) With great power comes great responsibility.
[2023-07-17 13:35:32,683] {subprocess.py:79} INFO - 
[2023-07-17 13:35:32,684] {subprocess.py:79} INFO - sudo: no tty present and no askpass program specified
[2023-07-17 13:35:32,697] {subprocess.py:79} INFO - User created
[2023-07-17 13:35:32,702] {subprocess.py:83} INFO - Command exited with return code 0
[2023-07-17 13:35:32,816] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=create_user, execution_date=20230622T090149, start_date=20230717T133530, end_date=20230717T133532
[2023-07-17 13:35:32,960] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-17 13:35:33,002] {local_task_job.py:151} INFO - Task exited with return code 0
