[2023-07-13 10:02:34,342] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-20T10:01:47+00:00 [queued]>
[2023-07-13 10:02:34,471] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-20T10:01:47+00:00 [queued]>
[2023-07-13 10:02:34,472] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 10:02:34,473] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-07-13 10:02:34,474] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 10:02:34,559] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): create_user> on 2023-06-20T10:01:47+00:00
[2023-07-13 10:02:34,566] {standard_task_runner.py:52} INFO - Started process 8846 to run task
[2023-07-13 10:02:34,581] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'create_user', '2023-06-20T10:01:47+00:00', '--job-id', '10828', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag/test.py', '--cfg-path', '/tmp/tmp9cy4ulsb', '--error-file', '/tmp/tmpp26u7zht']
[2023-07-13 10:02:34,584] {standard_task_runner.py:77} INFO - Job 10828: Subtask create_user
[2023-07-13 10:02:34,711] {logging_mixin.py:104} INFO - Running <TaskInstance: my_first_dag.create_user 2023-06-20T10:01:47+00:00 [running]> on host d9c3ec86c3ab
[2023-07-13 10:02:35,151] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=create_user
AIRFLOW_CTX_EXECUTION_DATE=2023-06-20T10:01:47+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-20T10:01:47+00:00
[2023-07-13 10:02:35,153] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-07-13 10:02:35,155] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\nid -u test_user;\nif [$? -eq o];\n    then echo "User exists"\nelse sudo useradd -r test_user;\n    echo "User created";\nfi']
[2023-07-13 10:02:35,168] {subprocess.py:75} INFO - Output:
[2023-07-13 10:02:35,244] {subprocess.py:79} INFO - id: ‘test_user’: no such user
[2023-07-13 10:02:35,252] {subprocess.py:79} INFO - bash: line 2: [1: command not found
[2023-07-13 10:02:35,327] {subprocess.py:79} INFO - 
[2023-07-13 10:02:35,328] {subprocess.py:79} INFO - We trust you have received the usual lecture from the local System
[2023-07-13 10:02:35,329] {subprocess.py:79} INFO - Administrator. It usually boils down to these three things:
[2023-07-13 10:02:35,330] {subprocess.py:79} INFO - 
[2023-07-13 10:02:35,331] {subprocess.py:79} INFO -     #1) Respect the privacy of others.
[2023-07-13 10:02:35,332] {subprocess.py:79} INFO -     #2) Think before you type.
[2023-07-13 10:02:35,332] {subprocess.py:79} INFO -     #3) With great power comes great responsibility.
[2023-07-13 10:02:35,333] {subprocess.py:79} INFO - 
[2023-07-13 10:02:35,334] {subprocess.py:79} INFO - sudo: no tty present and no askpass program specified
[2023-07-13 10:02:35,341] {subprocess.py:79} INFO - User created
[2023-07-13 10:02:35,345] {subprocess.py:83} INFO - Command exited with return code 0
[2023-07-13 10:02:35,428] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=create_user, execution_date=20230620T100147, start_date=20230713T100234, end_date=20230713T100235
[2023-07-13 10:02:35,513] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-13 10:02:35,561] {local_task_job.py:151} INFO - Task exited with return code 0
