[2023-07-13 06:18:37,383] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-19T18:01:52+00:00 [queued]>
[2023-07-13 06:18:37,522] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-19T18:01:52+00:00 [queued]>
[2023-07-13 06:18:37,523] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 06:18:37,524] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-07-13 06:18:37,524] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 06:18:37,581] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): create_user> on 2023-06-19T18:01:52+00:00
[2023-07-13 06:18:37,588] {standard_task_runner.py:52} INFO - Started process 88119 to run task
[2023-07-13 06:18:37,602] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'create_user', '2023-06-19T18:01:52+00:00', '--job-id', '9869', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag/test.py', '--cfg-path', '/tmp/tmp5o89hetv', '--error-file', '/tmp/tmpdqw2olpc']
[2023-07-13 06:18:37,604] {standard_task_runner.py:77} INFO - Job 9869: Subtask create_user
[2023-07-13 06:18:37,722] {logging_mixin.py:104} INFO - Running <TaskInstance: my_first_dag.create_user 2023-06-19T18:01:52+00:00 [running]> on host d9c3ec86c3ab
[2023-07-13 06:18:38,122] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=create_user
AIRFLOW_CTX_EXECUTION_DATE=2023-06-19T18:01:52+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-19T18:01:52+00:00
[2023-07-13 06:18:38,125] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-07-13 06:18:38,126] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\nid -u test_user;\nif [$? -eq o];\n    then echo "User exists"\nelse sudo useradd -r test_user;\n    echo "User created";\nfi']
[2023-07-13 06:18:38,140] {subprocess.py:75} INFO - Output:
[2023-07-13 06:18:38,217] {subprocess.py:79} INFO - id: ‘test_user’: no such user
[2023-07-13 06:18:38,226] {subprocess.py:79} INFO - bash: line 2: [1: command not found
[2023-07-13 06:18:38,293] {subprocess.py:79} INFO - 
[2023-07-13 06:18:38,294] {subprocess.py:79} INFO - We trust you have received the usual lecture from the local System
[2023-07-13 06:18:38,295] {subprocess.py:79} INFO - Administrator. It usually boils down to these three things:
[2023-07-13 06:18:38,296] {subprocess.py:79} INFO - 
[2023-07-13 06:18:38,297] {subprocess.py:79} INFO -     #1) Respect the privacy of others.
[2023-07-13 06:18:38,297] {subprocess.py:79} INFO -     #2) Think before you type.
[2023-07-13 06:18:38,298] {subprocess.py:79} INFO -     #3) With great power comes great responsibility.
[2023-07-13 06:18:38,299] {subprocess.py:79} INFO - 
[2023-07-13 06:18:38,300] {subprocess.py:79} INFO - sudo: no tty present and no askpass program specified
[2023-07-13 06:18:38,307] {subprocess.py:79} INFO - User created
[2023-07-13 06:18:38,311] {subprocess.py:83} INFO - Command exited with return code 0
[2023-07-13 06:18:38,380] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=create_user, execution_date=20230619T180152, start_date=20230713T061837, end_date=20230713T061838
[2023-07-13 06:18:38,457] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-13 06:18:38,498] {local_task_job.py:151} INFO - Task exited with return code 0
